### ISSUE TITLE
specify db to use on intantiation of client?

### ISSUE THREAD

**Issue by ralyodio** [dogukanakkaya/deno-elasticsearch#2]
I have two apps using elasticsearch, I'd like to keep them in different databases. is there a way to define that when I create the client in each app?

https://stackoverflow.com/questions/74123613/can-i-specify-database-in-uri-for-elasticsearch/74125109#74125109

**Comment by dogukanakkaya** [comment]
I answered the question in Stackoverflow. There is no `specifying database` and specifiying the index at the client instantiation is not possible and shouldn't be a necessary a future since you can already target the indices as you wish.
