### ISSUE TITLE
Documentation: search for multiple fields

### ISSUE THREAD

**Issue by nsadeh** [dogukanakkaya/deno-elasticsearch#3]
In an application I am writing I need to be able to match on multiple fields in an AND combination. I am pretty sure the example given for multiple fields is an OR (but I am not 100% sure). How would I go about saying "title: Deno and language: TypeScript", for example?

**Comment by dogukanakkaya** [comment]
You have the possibility to send all kind of queries in query object. It's directly sent to Elasticsearch. So you can search for [how to match multiple fields in Elasticsearch](https://stackoverflow.com/questions/39507005/query-with-match-by-multiple-fields).
Basically you should be able to that:
```ts
const res: SearchResponse<Source> = await client.search<Source>({
  target: "test-index",
  body: {
    query: {
      // send the query to match multiple fields,
    },
  },
});
```

**Comment by nsadeh** [comment]
Yea my bad, I was confused because I was trying to compare Node ES and Deno ES and I now realize that I can just look up the rest API. Thank you for bearing with me.
