### ISSUE TITLE
No support for apiKey auth

### ISSUE THREAD

**Issue by gnom1gnom** [dogukanakkaya/deno-elasticsearch#4]
Hello,
do you plan to support apiKey authentication? This is default for the official cloud.elastic.co.
```
import { Client as ElasticsearchClient } from "https://deno.land/x/elasticsearch@v8.3.3/mod.ts";

const client = new ElasticsearchClient({
  cloud: { id: 'myProject:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' },
  auth: { apiKey: 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy' }
});
```
Throws `Type '{ apiKey: string; }' is not assignable to type 'ClientAuth'.  Object literal may only specify known properties, and 'apiKey' does not exist in type 'ClientAuth'.`

**Comment by dogukanakkaya** [comment]
You can switch to `v8.6.0` to try out the new `apiKey` property in `auth` object.
